In [7]:
import torch
import numpy as np


In [3]:
x = torch.tensor([[1,2], [3,4]], device='cuda')
print(x.shape)
print(x.device)

torch.Size([2, 2])
cuda:0


In [3]:
np_arr = np.ones((2,3))
c = torch.from_numpy(np_arr)


c_ones = torch.ones_like(x)
# print(c)
print(f"Ones tensor: \n{c_ones} \n")

c_rand = torch.rand_like(x, dtype=torch.float)
print(f"Random tensor: \n{c_rand} \n")


Ones tensor: 
tensor([[1, 1],
        [1, 1]], device='cuda:0') 

Random tensor: 
tensor([[0.7257, 0.9203],
        [0.6696, 0.2277]], device='cuda:0') 



# Different tensors with based on a constant shape

In [29]:
shape = (4,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.0390, 0.9293, 0.4427],
        [0.4361, 0.5584, 0.5003],
        [0.1362, 0.8382, 0.3992],
        [0.4019, 0.7405, 0.0193]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


# tensor attributes

In [34]:
tensor = torch.rand(4,5)
print(f"Tensor shape {tensor.shape}")
print(f"Data type shape {tensor.dtype}")
print(f"Device tensor is stored {tensor.device}")

Tensor shape torch.Size([4, 5])
Data type shape torch.float32
Device tensor is stored cpu


# tensor operations

In [37]:
if torch.cuda.is_available():
    print(f"GPU name: {torch.cuda.get_device_name(0)}")
    print(f"Current device: {torch.cuda.current_device()}")

GPU name: Tesla T4
Current device: 0


In [21]:
# standard numpy-like indexing and slicing
test_tensor = torch.ones(5,5)
test_tensor[:,2] = 6
print(test_tensor)

tensor([[1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.]])


In [5]:
# joining tensors
t1 = torch.cat([test_tensor, test_tensor, test_tensor], dim=1)
t2 = torch.cat([test_tensor, test_tensor, test_tensor], dim=0)
print(t1)
print(t2)

tensor([[1., 1., 6., 1., 1., 1., 1., 6., 1., 1., 1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1., 1., 1., 6., 1., 1., 1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1., 1., 1., 6., 1., 1., 1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1., 1., 1., 6., 1., 1., 1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1., 1., 1., 6., 1., 1., 1., 1., 6., 1., 1.]])
tensor([[1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.],
        [1., 1., 6., 1., 1.]])


# arithmetic operations

In [19]:
arth_tensor_1 = torch.tensor([[1,2],[3,4]], dtype=torch.float32)
print(arth_tensor_1)
# transpose of matrix
tranpose_arth_tensor_1 = arth_tensor_1.T
print(tranpose_arth_tensor_1)

# matrix multiplication
t3 = arth_tensor_1 @ tranpose_arth_tensor_1
                    # or    
t4 = arth_tensor_1.matmul(tranpose_arth_tensor_1)
print(t3)


# element-wise multiplication
t5 = arth_tensor_1 * tranpose_arth_tensor_1
                # or
t6 = arth_tensor_1.mul(tranpose_arth_tensor_1)
print(t5)


t7 = torch.rand_like(arth_tensor_1)
torch.mul(arth_tensor_1,arth_tensor_1, out=t7)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 3.],
        [2., 4.]])
tensor([[ 5., 11.],
        [11., 25.]])
tensor([[ 1.,  6.],
        [ 6., 16.]])


tensor([[ 1.,  4.],
        [ 9., 16.]])

# single element tensor

In [31]:
my_tensor = torch.tensor([[2,4],[6,8]], dtype=torch.float32)
# a single tensor (which is the sum of my_tensor)
agg = my_tensor.sum()
print(f"single tensor \n {agg} \n")

# converting tensor into a numerical value
agg_item = agg.item()
print(agg_item, type(agg_item))

single tensor 
 20.0 

20.0 <class 'float'>


# in-place operations
- operations that modify a tensor directly instead of creating a new tensor and returning it
- they are suffixed by '_'

In [4]:
test_tensor_1 = torch.tensor([[3,6],[9,12]], dtype=torch.float32)

tensor_plus_five = test_tensor_1.add_(5)
print(f"new tensor with 5 added to each element \n {tensor_plus_five} \n")

tensor_power_two = test_tensor_1.pow_(2)
print(f"new tensor with elements raised to the power 2 \n {tensor_power_two} \n")

tensor_div_3 = test_tensor_1.div_(2)
print(f"new tensor with elements divided by 3 \n {tensor_div_3} \n")

new tensor with 5 added to each element 
 tensor([[ 8., 11.],
        [14., 17.]]) 

new tensor with elements raised to the power 2 
 tensor([[ 64., 121.],
        [196., 289.]]) 

new tensor with elements divided by 3 
 tensor([[ 32.0000,  60.5000],
        [ 98.0000, 144.5000]]) 



# bride with numpy and tensor

* tensor to numpy array

In [6]:
test_tensor_2 = torch.ones(4)
print(f"t: {test_tensor_2} \n")

n = test_tensor_2.numpy()
print(f"n: {n} \n")

t: tensor([1., 1., 1., 1.]) 

n: [1. 1. 1. 1.] 



- numpy array to tensor

In [9]:
n_array = np.ones(5)
print(n_array)

t8 = torch.from_numpy(n_array)
print(t8)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
