In [ ]:
import torch
import numpy as np


True


In [19]:
x = torch.tensor([[1,2], [3,4]], device='cuda')
print(x.shape)
print(x.device)

torch.Size([2, 2])
cuda:0


In [27]:
np_arr = np.ones((2,3))
c = torch.from_numpy(np_arr)


c_ones = torch.ones_like(x)
# print(c)
print(f"Ones tensor: \n{c_ones} \n")

c_rand = torch.rand_like(x, dtype=torch.float)
print(f"Random tensor: \n{c_rand} \n")


Ones tensor: 
tensor([[1, 1],
        [1, 1]], device='cuda:0') 

Random tensor: 
tensor([[0.6402, 0.6815],
        [0.8201, 0.0792]], device='cuda:0') 



# Different tensors with based on a constant shape

In [28]:
shape = (4,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.7937, 0.6811, 0.5192],
        [0.9168, 0.1634, 0.3863],
        [0.2610, 0.2603, 0.7151],
        [0.8980, 0.0680, 0.0457]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
